### ISSUE TITLE
Uploading file doesn't work on demo env

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#12]
Hi,
I have written the following script:
```
create application Stockage

create entity Product
add field Nom

entity Product has one Documents
select entity Documents
add field Manuel with type file
add field Tutorial with type file
add field Photo with type image
```

When I try to upload files in documents, I have an error.
```
2021-05-13 17:31:23-155:  GET /login?r=/dossier/show?id=1 200 12.907 ms - 5717
2021-05-13 17:34:04-299:  MulterError: Unexpected field
    at wrappedFileFilter (/app/workspace/node_modules/multer/index.js:40:19)
    at Busboy. (/app/workspace/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:315:20)
    at Busboy.emit (/app/workspace/node_modules/busboy/lib/main.js:38:33)
    at PartStream. (/app/workspace/node_modules/busboy/lib/types/multipart.js:213:13)
    at PartStream.emit (events.js:315:20)
    at HeaderParser. (/app/workspace/node_modules/dicer/lib/Dicer.js:51:16)
    at HeaderParser.emit (events.js:315:20)
    at HeaderParser._finish (/app/workspace/node_modules/dicer/lib/HeaderParser.js:68:8)
    at SBMH. (/app/workspace/node_modules/dicer/lib/HeaderParser.js:40:12)
    at SBMH.emit (events.js:315:20)
    at SBMH._sbmh_feed (/app/workspace/node_modules/streamsearch/lib/sbmh.js:159:14)
    at SBMH.push (/app/workspace/node_modules/streamsearch/lib/sbmh.js:56:14)
    at HeaderParser.push (/app/workspace/node_modules/dicer/lib/HeaderParser.js:46:19)
    at Dicer._oninfo (/app/workspace/node_modules/dicer/lib/Dicer.js:197:25)
    at SBMH. (/app/workspace/node_modules/dicer/lib/Dicer.js:127:10)

2021-05-13 17:34:04-300:  POST /classeur/create?ajax=true&associationAlias=r_classeur&associationForeignKey=fk_id_classeur&associationFlag=1&associationSource=e_dossier&associationUrl=dossier& 500 78.525 ms - 1563
```
Any idea ?

**Comment by EoiFirst** [comment]
Hi,

This error normaly occurs when multer finds a file in the request body but it doesn't exists in the `models/attributes/entity.json` file of your entity.

Files found in body should match a field definition with a `newmipsType` set to 'file' or 'picture' in your attributes configuration.

Does it help you fix your issue ?

**Comment by slidebend** [comment]
Initial script was in french. 
NewmipsType has been set to value "fichier".
I suspect this is the origin of the issue.

**Comment by slidebend** [comment]
Fixed. Thx
