### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by slidebend** [nodea-software/nodea#20]
Hi,
I have created a module called "Evaluation"
I want to request my database and send data to the main module page.
Therefore, I have overload code of route "routes/evaluation.js" to execute sequelize query:
```
	main() {
		
		this.router.get(`/${this.moduleName}`, this.asyncRoute(async(data) => {
			
			console.log('inside');
			let include = [{
				model: models.E_etape,
				as: "r_etapes",
				include: [{
					model: models.E_question,
					as: "r_question",
					include: [{
						model: models.E_reponse,
						as: "r_reponses"
					}]
				}]
			}];
			const questionnaire = await models.E_questionnaire.findOne({where: {id: 1}, include: include});

			data.res.success(_ => data.res.render(`modules/m_${this.moduleName}`, questionnaire));
		}));
	}
```
I encounter a Dust error :
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'include' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.contextDump (/app/workspace/node_modules/dustjs-helpers/lib/dust-helpers.js:221:19)
    at Chunk.helper (/app/workspace/node_modules/dustjs-linkedin/lib/dust.js:928:33)
    at body_2 (evalmachine.<anonymous>:1:1140)
    at Chunk.block (/app/workspace/node_modules/dustjs-linkedin/lib/dust.js:881:14)
    at body_0 (evalmachine.<anonymous>:1:7910)
    at done (/app/workspace/node_modules/dustjs-linkedin/lib/dust.js:176:13)
    at /app/workspace/a_positionnement/_core/library/consolidate.js:101:3
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```
Is it the right way to overload module code ? How to avoid the circular parsing ?

Thank you for your help.

**Comment by slidebend** [comment]
Simply passing result of query in a JSON object solved the issue. See below:
```
data.res.success(_ => data.res.render(`modules/m_${this.moduleName}`, {"questionnaire": questionnaire}));
```
